Compiled from "FailedFuture.java"
public final class io.netty.util.concurrent.FailedFuture<V> extends io.netty.util.concurrent.CompleteFuture<V> {
  private final java.lang.Throwable cause;

  public io.netty.util.concurrent.FailedFuture(io.netty.util.concurrent.EventExecutor, java.lang.Throwable);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #13                 // Method io/netty/util/concurrent/CompleteFuture."<init>":(Lio/netty/util/concurrent/EventExecutor;)V
       5: aload_2
       6: ifnonnull     19
       9: new           #15                 // class java/lang/NullPointerException
      12: dup
      13: ldc           #16                 // String cause
      15: invokespecial #19                 // Method java/lang/NullPointerException."<init>":(Ljava/lang/String;)V
      18: athrow
      19: aload_0
      20: aload_2
      21: putfield      #25                 // Field cause:Ljava/lang/Throwable;
      24: return

  public java.lang.Throwable cause();
    Code:
       0: aload_0
       1: getfield      #25                 // Field cause:Ljava/lang/Throwable;
       4: areturn

  public boolean isSuccess();
    Code:
       0: iconst_0
       1: ireturn

  public io.netty.util.concurrent.Future<V> sync();
    Code:
       0: aload_0
       1: getfield      #25                 // Field cause:Ljava/lang/Throwable;
       4: invokestatic  #41                 // Method io/netty/util/internal/PlatformDependent.throwException:(Ljava/lang/Throwable;)V
       7: aload_0
       8: areturn

  public io.netty.util.concurrent.Future<V> syncUninterruptibly();
    Code:
       0: aload_0
       1: getfield      #25                 // Field cause:Ljava/lang/Throwable;
       4: invokestatic  #41                 // Method io/netty/util/internal/PlatformDependent.throwException:(Ljava/lang/Throwable;)V
       7: aload_0
       8: areturn

  public V getNow();
    Code:
       0: aconst_null
       1: areturn
}
