Compiled from "FailedFuture.java"
public final class io.netty.util.concurrent.FailedFuture<V> extends io.netty.util.concurrent.CompleteFuture<V> {
  private final java.lang.Throwable cause;

  public io.netty.util.concurrent.FailedFuture(io.netty.util.concurrent.EventExecutor, java.lang.Throwable);
    Code:
       0: aload_0
       1: aload_1
       2: invokespecial #13                 // Method io/netty/util/concurrent/CompleteFuture."<init>":(Lio/netty/util/concurrent/EventExecutor;)V
       5: aload_0
       6: aload_2
       7: ldc           #14                 // String cause
       9: invokestatic  #20                 // Method io/netty/util/internal/ObjectUtil.checkNotNull:(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
      12: checkcast     #22                 // class java/lang/Throwable
      15: putfield      #24                 // Field cause:Ljava/lang/Throwable;
      18: return

  public java.lang.Throwable cause();
    Code:
       0: aload_0
       1: getfield      #24                 // Field cause:Ljava/lang/Throwable;
       4: areturn

  public boolean isSuccess();
    Code:
       0: iconst_0
       1: ireturn

  public io.netty.util.concurrent.Future<V> sync();
    Code:
       0: aload_0
       1: getfield      #24                 // Field cause:Ljava/lang/Throwable;
       4: invokestatic  #41                 // Method io/netty/util/internal/PlatformDependent.throwException:(Ljava/lang/Throwable;)V
       7: aload_0
       8: areturn

  public io.netty.util.concurrent.Future<V> syncUninterruptibly();
    Code:
       0: aload_0
       1: getfield      #24                 // Field cause:Ljava/lang/Throwable;
       4: invokestatic  #41                 // Method io/netty/util/internal/PlatformDependent.throwException:(Ljava/lang/Throwable;)V
       7: aload_0
       8: areturn

  public V getNow();
    Code:
       0: aconst_null
       1: areturn
}
