Compiled from "Exception.scala"
public final class scala.util.control.Exception$$anonfun$handling$1 extends scala.runtime.AbstractFunction1<scala.Function1<java.lang.Throwable, T>, scala.util.control.Exception$Catch<T>> implements scala.Serializable {
  public static final long serialVersionUID;

  private final scala.collection.Seq exceptions$2;

  public final scala.util.control.Exception$Catch<T> apply(scala.Function1<java.lang.Throwable, T>);
    Code:
       0: getstatic     #25                 // Field scala/util/control/Exception$.MODULE$:Lscala/util/control/Exception$;
       3: aload_1
       4: aload_0
       5: getfield      #27                 // Field exceptions$2:Lscala/collection/Seq;
       8: invokevirtual #31                 // Method scala/util/control/Exception$.scala$util$control$Exception$$fun$1:(Lscala/Function1;Lscala/collection/Seq;)Lscala/util/control/Exception$Catch;
      11: areturn

  public final java.lang.Object apply(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     #38                 // class scala/Function1
       5: invokevirtual #40                 // Method apply:(Lscala/Function1;)Lscala/util/control/Exception$Catch;
       8: areturn

  public scala.util.control.Exception$$anonfun$handling$1(scala.collection.Seq);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #27                 // Field exceptions$2:Lscala/collection/Seq;
       5: aload_0
       6: invokespecial #47                 // Method scala/runtime/AbstractFunction1."<init>":()V
       9: return
}
