Compiled from "Exception.scala"
public final class scala.util.control.Exception$$anonfun$throwableSubtypeToCatcher$2 extends scala.runtime.AbstractFunction1<Ex, T> implements scala.Serializable {
  public static final long serialVersionUID;

  private final scala.PartialFunction pf$1;

  public final T apply(Ex);
    Code:
       0: aload_0
       1: getfield      #23                 // Field pf$1:Lscala/PartialFunction;
       4: aload_1
       5: invokeinterface #28,  2           // InterfaceMethod scala/PartialFunction.apply:(Ljava/lang/Object;)Ljava/lang/Object;
      10: areturn

  public final java.lang.Object apply(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     #34                 // class java/lang/Throwable
       5: invokevirtual #36                 // Method apply:(Ljava/lang/Throwable;)Ljava/lang/Object;
       8: areturn

  public scala.util.control.Exception$$anonfun$throwableSubtypeToCatcher$2(scala.PartialFunction);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #23                 // Field pf$1:Lscala/PartialFunction;
       5: aload_0
       6: invokespecial #42                 // Method scala/runtime/AbstractFunction1."<init>":()V
       9: return
}
