Compiled from "Exception.scala"
public final class scala.util.control.Exception$Catch$$anonfun$opt$1 extends scala.runtime.AbstractFunction0<scala.Some<U>> implements scala.Serializable {
  public static final long serialVersionUID;

  private final scala.Function0 body$1;

  public final scala.Some<U> apply();
    Code:
       0: new           #23                 // class scala/Some
       3: dup
       4: aload_0
       5: getfield      #25                 // Field body$1:Lscala/Function0;
       8: invokeinterface #30,  1           // InterfaceMethod scala/Function0.apply:()Ljava/lang/Object;
      13: invokespecial #34                 // Method scala/Some."<init>":(Ljava/lang/Object;)V
      16: areturn

  public final java.lang.Object apply();
    Code:
       0: aload_0
       1: invokevirtual #38                 // Method apply:()Lscala/Some;
       4: areturn

  public scala.util.control.Exception$Catch$$anonfun$opt$1(scala.util.control.Exception$Catch<T>);
    Code:
       0: aload_0
       1: aload_2
       2: putfield      #25                 // Field body$1:Lscala/Function0;
       5: aload_0
       6: invokespecial #42                 // Method scala/runtime/AbstractFunction0."<init>":()V
       9: return
}
