Compiled from "CancellationException.kt"
public final class kotlin.coroutines.cancellation.CancellationExceptionKt {
  private static final java.util.concurrent.CancellationException CancellationException(java.lang.String, java.lang.Throwable);
    Code:
       0: new           #12                 // class java/util/concurrent/CancellationException
       3: dup
       4: aload_0
       5: invokespecial #16                 // Method java/util/concurrent/CancellationException."<init>":(Ljava/lang/String;)V
       8: astore_2
       9: aload_2
      10: astore_3
      11: iconst_0
      12: istore        4
      14: aload_3
      15: aload_1
      16: invokevirtual #20                 // Method java/util/concurrent/CancellationException.initCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;
      19: pop
      20: aload_2
      21: areturn

  private static final java.util.concurrent.CancellationException CancellationException(java.lang.Throwable);
    Code:
       0: new           #12                 // class java/util/concurrent/CancellationException
       3: dup
       4: aload_0
       5: dup
       6: ifnull        15
       9: invokevirtual #35                 // Method java/lang/Throwable.toString:()Ljava/lang/String;
      12: goto          17
      15: pop
      16: aconst_null
      17: invokespecial #16                 // Method java/util/concurrent/CancellationException."<init>":(Ljava/lang/String;)V
      20: astore_1
      21: aload_1
      22: astore_2
      23: iconst_0
      24: istore_3
      25: aload_2
      26: aload_0
      27: invokevirtual #20                 // Method java/util/concurrent/CancellationException.initCause:(Ljava/lang/Throwable;)Ljava/lang/Throwable;
      30: pop
      31: aload_1
      32: areturn

  public static void CancellationException$annotations();
    Code:
       0: return
}
